insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');
insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');
insert into pessoa(nome,senha,email) VALUES('Andreg','als','12');
insert into pessoa(nome,senha,email) VALUES('Andreh','als','12');
insert into pessoa(nome,senha,email) VALUES('Andreg','als','12');
insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');
insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');
insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');
insert into pessoa(nome,senha,email) VALUES('Andre1','als','12');